# -*- coding: utf-8 -*-
"""DAccutic (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12oN4Lb1WNIKQgo79pEf0AXT5G8I_5nT5
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#importing the csv
df = pd.read_csv('adult.csv')
df.head()

df.shape

# Renaming the attributes
df = df.set_axis(['Age','Workclass','FNLWGT','Education','Edu_No.','Marital_Status','Occupation','Relationship','Race','Sex','Cptl_Gain','Cptl_Loss','Hours_p/w','Country','Income'],axis = 1)
df.head()

df.drop(['Marital_Status','Relationship','Race','Sex','Country'],axis=1,inplace=True)
df.head()

# Encoding the categorical values
from sklearn.preprocessing import LabelEncoder

le_workclass = LabelEncoder()
le_education = LabelEncoder()
le_occupation = LabelEncoder()
le_income = LabelEncoder()

df['Workclass_n'] = le_workclass.fit_transform(df['Workclass'])
df['Education_n'] = le_education.fit_transform(df['Education'])
df['Occupation_n'] = le_occupation.fit_transform(df['Occupation'])
df['Income_n'] = le_income.fit_transform(df['Income'])
df.drop(['Workclass','Education','Occupation','Income'], axis='columns',inplace=True)
df

x = df.iloc[:,:-1] #ind
y = df.iloc[:,-1]  #dep
print(type(x))
print(type(y))
print(x.shape)
print(y.shape)

#splitting the dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

# 1 --> Applying Decision Tree Model
from sklearn.tree import DecisionTreeClassifier

mod1 = DecisionTreeClassifier(criterion='gini')
mod1.fit(x_train,y_train)

#Accuracy
print("Training_Score",mod1.score(x_train,y_train))
print("Testing_Score",mod1.score(x_test,y_test))

# Computing the % of misclassification
mc_m1= 1 - mod1.score(x_test,y_test)
print('Misclassification Error = ',mc_m1* 100,'%')

# Testing the Decision Tree
ypred_m1 = mod1.predict(x_test)
print(ypred_m1)

# Computing Confusion Matrix & Classification Report
from sklearn.metrics import confusion_matrix, classification_report
c_m1 = confusion_matrix(y_test,ypred_m1)
print(c_m1)
print(classification_report(y_test,ypred_m1))

# 2. --> Applying Random Forest Classifer
from sklearn.ensemble import RandomForestClassifier

mod2 = RandomForestClassifier(n_estimators=60,criterion='entropy')
mod2.fit(x_train,y_train)

#Accuracy
print("Training_Score",mod2.score(x_train,y_train))
print("Testing_Score",mod2.score(x_test,y_test))

# Computing the % of misclassification
mc_m2 = 1 - mod2.score(x_test,y_test)
print('Misclassification Error = ',mc_m2* 100,'%')

# Testing Random Forest
ypred_m2 = mod2.predict(x_test)
print(ypred_m2)

# Computing Confusion Matrix & Classification Report
from sklearn.metrics import confusion_matrix, classification_report
c_m2 = confusion_matrix(y_test,ypred_m2)
print(c_m2)
print(classification_report(y_test,ypred_m2))

# 3. --> Applying KNN Classifer
from sklearn.neighbors import KNeighborsClassifier

mod3 = KNeighborsClassifier(n_neighbors=85)
mod3.fit(x_train,y_train)

#Accuracy
print("Training_Score",mod3.score(x_train,y_train))
print("Testing_Score",mod3.score(x_test,y_test))

# Computing the % of misclassification
mc_m3 = 1 - mod3.score(x_test,y_test)
print('Misclassification Error = ',mc_m3 * 100,'%')

# Testing the KNN
ypred_m3 = mod3.predict(x_test)
print(ypred_m3)

# Computing Confusion Matrix & Classification Report
from sklearn.metrics import confusion_matrix, classification_report
c_m3 = confusion_matrix(y_test,ypred_m3)
print(c_m3)
print(classification_report(y_test,ypred_m3))

# 4. --> Applying Naive Bayes
from sklearn.naive_bayes import GaussianNB

mod4 = GaussianNB()
mod4.fit(x_train,y_train)

#Accuracy
print("Training_Score",mod4.score(x_train,y_train))
print("Testing_Score",mod4.score(x_test,y_test))

# Computing the % of misclassification
mc_m4 = 1 - mod4.score(x_test,y_test)
print('Misclassification Error = ',mc_m4 * 100,'%')

# Testing Naive Bayes
ypred_m4 = mod4.predict(x_test)
print(ypred_m4)

# Computing Confusion Matrix & Classification Report
from sklearn.metrics import confusion_matrix, classification_report
c_m4 = confusion_matrix(y_test,ypred_m4)
print(c_m4)
print(classification_report(y_test,ypred_m4))

# 5. --> Applying Logistic Regression
from sklearn.linear_model import LogisticRegression

mod5 = LogisticRegression(solver="liblinear")
mod5.fit(x_train,y_train)

#Accuracy
print("Training_Score",mod5.score(x_train,y_train))
print("Testing_Score",mod5.score(x_test,y_test))

# Computing the % of misclassification
mc_m5 = 1 - mod5.score(x_test,y_test)
print('Misclassification Error = ',mc_m5 * 100,'%')

ypred_m5 = mod5.predict(x_test)
print(ypred_m4)

# Computing Confusion Matrix & Classification Report
from sklearn.metrics import confusion_matrix, classification_report
c_m5 = confusion_matrix(y_test,ypred_m5)
print(c_m5)
print(classification_report(y_test,ypred_m5))

result = min(mc_m1, mc_m2, mc_m3, mc_m4, mc_m5)
if result == mc_m1:
    print("Decision Tree has the best accuracy i.e. :", mod1.score(x_test, y_test) * 100, "%")
elif result == mc_m2:
    print("Random Forest has the best accuracy i.e. :", mod2.score(x_test, y_test) * 100, "%")
elif result == mc_m3:
    print("KNN has the best accuracy i.e. :", mod3.score(x_test, y_test) * 100, "%")
elif result == mc_m4:
    print("Naive Bayes has the best accuracy i.e. :", mod4.score(x_test, y_test) * 100, "%")
else:
    print("Logistic Regression has the best accuracy i.e. :", mod5.score(x_test, y_test) * 100, "%")

